import { z } from 'zod';

export const settingsSchema = z.object({
  site_name: z.string().min(1, 'Le nom du site est requis'),
  site_tagline_fr: z.string().optional(),
  site_tagline_en: z.string().optional(),
  site_tagline_ar: z.string().optional(),
  logo_url: z.string().optional(),
  favicon_url: z.string().optional(),
  primary_color: z.string().regex(/^#[0-9A-Fa-f]{6}$/, 'Couleur hex invalide'),
  secondary_color: z.string().regex(/^#[0-9A-Fa-f]{6}$/, 'Couleur hex invalide'),
  accent_color: z.string().regex(/^#[0-9A-Fa-f]{6}$/, 'Couleur hex invalide'),
  contact_email: z.string().email('Email invalide').optional().or(z.literal('')),
  contact_phone: z.string().optional(),
  whatsapp_number: z.string().optional(),
  business_address: z.string().optional(),
  facebook_url: z.string().url('URL invalide').optional().or(z.literal('')),
  instagram_url: z.string().url('URL invalide').optional().or(z.literal('')),
  tiktok_url: z.string().url('URL invalide').optional().or(z.literal('')),
  telegram_url: z.string().url('URL invalide').optional().or(z.literal('')),
  youtube_url: z.string().url('URL invalide').optional().or(z.literal('')),
  telegram_bot_token: z.string().optional(),
  telegram_chat_id: z.string().optional(),
  notification_email: z.string().email('Email invalide').optional().or(z.literal('')),
  meta_pixel_id: z.string().optional(),
  meta_capi_access_token: z.string().optional(),
  meta_dataset_id: z.string().optional(),
  google_analytics_id: z.string().optional(),
  google_ads_id: z.string().optional(),
  tiktok_pixel_id: z.string().optional(),
  default_currency: z.string().optional(),
  default_locale: z.enum(['fr', 'en', 'ar']).optional(),
  thank_you_message_fr: z.string().optional(),
  thank_you_message_en: z.string().optional(),
  thank_you_message_ar: z.string().optional(),
  cod_badge_fr: z.string().optional(),
  cod_badge_en: z.string().optional(),
  cod_badge_ar: z.string().optional(),
  // Announcement bar
  announcement_enabled: z.boolean().optional(),
  announcement_text_fr: z.string().optional(),
  announcement_text_en: z.string().optional(),
  announcement_text_ar: z.string().optional(),
  // Hero section
  hero_eyebrow_fr: z.string().optional(),
  hero_eyebrow_en: z.string().optional(),
  hero_eyebrow_ar: z.string().optional(),
  hero_title_accent_fr: z.string().optional(),
  hero_title_accent_en: z.string().optional(),
  hero_title_accent_ar: z.string().optional(),
  hero_title_main_fr: z.string().optional(),
  hero_title_main_en: z.string().optional(),
  hero_title_main_ar: z.string().optional(),
  hero_subtitle_fr: z.string().optional(),
  hero_subtitle_en: z.string().optional(),
  hero_subtitle_ar: z.string().optional(),
  hero_image_url: z.string().optional(),
  // Trust strip
  trust_1_title_fr: z.string().optional(),
  trust_1_title_en: z.string().optional(),
  trust_1_title_ar: z.string().optional(),
  trust_1_sub_fr: z.string().optional(),
  trust_1_sub_en: z.string().optional(),
  trust_1_sub_ar: z.string().optional(),
  trust_2_title_fr: z.string().optional(),
  trust_2_title_en: z.string().optional(),
  trust_2_title_ar: z.string().optional(),
  trust_2_sub_fr: z.string().optional(),
  trust_2_sub_en: z.string().optional(),
  trust_2_sub_ar: z.string().optional(),
  trust_3_title_fr: z.string().optional(),
  trust_3_title_en: z.string().optional(),
  trust_3_title_ar: z.string().optional(),
  trust_3_sub_fr: z.string().optional(),
  trust_3_sub_en: z.string().optional(),
  trust_3_sub_ar: z.string().optional(),
  trust_1_icon: z.string().optional(),
  trust_2_icon: z.string().optional(),
  trust_3_icon: z.string().optional(),
  // Featured section
  featured_section_title_fr: z.string().optional(),
  featured_section_title_en: z.string().optional(),
  featured_section_title_ar: z.string().optional(),
  featured_section_subtitle_fr: z.string().optional(),
  featured_section_subtitle_en: z.string().optional(),
  featured_section_subtitle_ar: z.string().optional(),
  why_us_title_fr: z.string().optional(),
  why_us_title_en: z.string().optional(),
  why_us_title_ar: z.string().optional(),
  why_us_sub_fr: z.string().optional(),
  why_us_sub_en: z.string().optional(),
  why_us_sub_ar: z.string().optional(),
  footer_description_fr: z.string().optional(),
  footer_description_en: z.string().optional(),
  footer_description_ar: z.string().optional(),
  whatsapp_default_message_fr: z.string().optional(),
  whatsapp_default_message_en: z.string().optional(),
  whatsapp_default_message_ar: z.string().optional(),
});

export type SettingsFormData = z.infer<typeof settingsSchema>;
